DEFAULT_LANG = "en"

TEXTS = {
    "en": {
        "choose_language": "🌐 Please choose your language:",
        "language_set": "✅ Language set to English",
        "menu": "👟 <b>SneakerShop</b>\n\nWhat are we looking for today?",
        "btn_catalog": "🛍 Catalog",
        "btn_cart": "🛒 Cart",
        "btn_orders": "🧾 My Orders",
        "btn_ai": "🤖 AI Assistant",
        "btn_language": "🌐 Language",
        "soon": "🚧 Coming soon",
        "catalog_title": "🛍 <b>Catalog</b>\n\nChoose a category:",
        "in_stock": "In stock",
        "empty_category": "No products in this category yet.",
        "btn_add_cart": "🛒 Add to cart",
        "btn_categories": "⬅️ Categories",
        "btn_menu": "🏠 Menu",
        "cart_title": "🛒 <b>Your Cart</b>",
        "cart_empty": "🛒 Your cart is empty.",
        "cart_total": "Total",
        "added_to_cart": "✅ Added to cart",
        "btn_checkout": "💳 Checkout",
        "btn_clear": "🗑 Clear cart",
        "checkout_name": "📝 Please enter your <b>full name</b>:",
        "checkout_phone": "📞 Now enter your <b>phone number</b>:",
        "checkout_address": "🏠 Finally, your <b>delivery address</b>:",
        "checkout_confirm": "🧾 <b>Please confirm your order:</b>",
        "order_placed": "✅ Order #{id} placed!\nWe'll contact you shortly. Thank you! 🙌",
        "order_cancelled": "❌ Order cancelled.",
        "btn_confirm": "✅ Confirm",
        "btn_cancel": "❌ Cancel",
        "orders_title": "🧾 <b>My Orders</b>",
        "orders_empty": "🧾 You have no orders yet.",
        "status_new": "🆕 New",
        "status_paid": "💳 Paid",
        "status_shipped": "🚚 Shipped",
        "status_done": "✅ Done",
        "status_cancelled": "❌ Cancelled",
        "admin_title": "🛠 <b>Admin Panel</b>",
        "admin_orders": "📦 Orders",
        "admin_add_product": "➕ Add Product",
        "admin_stats": "📊 Statistics",
        "admin_no_orders": "No orders yet.",
        "status_changed": "✅ Status updated",
        "btn_back": "⬅️ Back",
    },
    "ru": {
        "choose_language": "🌐 Выберите язык:",
        "language_set": "✅ Язык переключён на русский",
        "menu": "👟 <b>SneakerShop</b>\n\nЧто будем искать сегодня?",
        "btn_catalog": "🛍 Каталог",
        "btn_cart": "🛒 Корзина",
        "btn_orders": "🧾 Мои заказы",
        "btn_ai": "🤖 AI-консультант",
        "btn_language": "🌐 Язык",
        "soon": "🚧 Скоро будет",
        "catalog_title": "🛍 <b>Каталог</b>\n\nВыберите категорию:",
        "in_stock": "В наличии",
        "empty_category": "В этой категории пока нет товаров.",
        "btn_add_cart": "🛒 В корзину",
        "btn_categories": "⬅️ Категории",
        "btn_menu": "🏠 Меню",
        "cart_title": "🛒 <b>Ваша корзина</b>",
        "cart_empty": "🛒 Ваша корзина пуста.",
        "cart_total": "Итого",
        "added_to_cart": "✅ Добавлено в корзину",
        "btn_checkout": "💳 Оформить заказ",
        "btn_clear": "🗑 Очистить корзину",
        "checkout_name": "📝 Введите ваше <b>имя и фамилию</b>:",
        "checkout_phone": "📞 Теперь введите <b>номер телефона</b>:",
        "checkout_address": "🏠 И наконец, <b>адрес доставки</b>:",
        "checkout_confirm": "🧾 <b>Подтвердите заказ:</b>",
        "order_placed": "✅ Заказ #{id} оформлен!\nМы скоро свяжемся с вами. Спасибо! 🙌",
        "order_cancelled": "❌ Заказ отменён.",
        "btn_confirm": "✅ Подтвердить",
        "btn_cancel": "❌ Отмена",
        "orders_title": "🧾 <b>Мои заказы</b>",
        "orders_empty": "🧾 У вас пока нет заказов.",
        "status_new": "🆕 Новый",
        "status_paid": "💳 Оплачен",
        "status_shipped": "🚚 Отправлен",
        "status_done": "✅ Выполнен",
        "status_cancelled": "❌ Отменён",
        "admin_title": "🛠 <b>Админ-панель</b>",
        "admin_orders": "📦 Заказы",
        "admin_add_product": "➕ Добавить товар",
        "admin_stats": "📊 Статистика",
        "admin_no_orders": "Заказов пока нет.",
        "status_changed": "✅ Статус обновлён",
        "btn_back": "⬅️ Назад",
    },
}


def t(key: str, lang: str) -> str:
    return TEXTS.get(lang, TEXTS[DEFAULT_LANG]).get(key, key)


def status_label(status: str, lang: str) -> str:
    return t(f"status_{status}", lang)


STATUSES = ("new", "paid", "shipped", "done", "cancelled")
