DEFAULT_LANG = "en"

TEXTS = {
    "en": {
        "choose_language": "🌐 Please choose your language:",
        "language_set": "✅ Language set to English",
        "menu": "👟 <b>SneakerShop</b>\n\nWhat are we looking for today?",
        "welcome": "👟 <b>Welcome to SneakerShop!</b>\n\nYour favorite sneakers, delivered fast 🚚\nUse the menu below to start shopping.\n\n💡 /menu — open the menu anytime",
        "btn_catalog": "🛍 Catalog",
        "btn_cart": "🛒 Cart",
        "btn_orders": "🧾 My Orders",
        "btn_ai": "🤖 AI Assistant",
        "btn_language": "🌐 Language",
        "soon": "🚧 Coming soon",
        "catalog_title": "🛍 <b>Catalog</b>\n\nChoose a category:",
        "in_stock": "In stock",
        "empty_category": "No products in this category yet.",
        "btn_add_cart": "🛒 Add to cart",
        "btn_categories": "⬅️ Categories",
        "btn_menu": "🏠 Menu",
        "cart_title": "🛒 <b>Your Cart</b>",
        "cart_empty": "🛒 Your cart is empty.",
        "cart_total": "Total",
        "added_to_cart": "✅ Added to cart",
        "btn_checkout": "💳 Checkout",
        "btn_clear": "🗑 Clear cart",
        "checkout_name": "📝 Please enter your <b>full name</b>:",
        "checkout_phone": "📞 Now enter your <b>phone number</b>:",
        "checkout_address": "🏠 Finally, your <b>delivery address</b>:",
        "checkout_confirm": "🧾 <b>Please confirm your order:</b>",
        "order_placed": "✅ Order #{id} placed!\nWe'll contact you shortly. Thank you! 🙌",
        "order_cancelled": "❌ Order cancelled.",
        "btn_confirm": "✅ Confirm",
        "btn_cancel": "❌ Cancel",
        "orders_title": "🧾 <b>My Orders</b>",
        "orders_empty": "🧾 You have no orders yet.",
        "status_new": "🆕 New",
        "status_paid": "💳 Paid",
        "status_shipped": "🚚 Shipped",
        "status_done": "✅ Done",
        "status_cancelled": "❌ Cancelled",
        "admin_title": "🛠 <b>Admin Panel</b>",
        "admin_orders": "📦 Orders",
        "admin_add_product": "➕ Add Product",
        "admin_stats": "📊 Statistics",
        "admin_no_orders": "No orders yet.",
        "admin_no_products": "No products yet.",
        "status_changed": "✅ Status updated",
        "btn_back": "⬅️ Back",
        "admin_delete": "🗑 Delete Product",
        "add_choose_category": "🗂 Choose a category:",
        "add_name": "📝 Enter product <b>name</b>:",
        "add_brand": "🏷 Enter <b>brand</b>:",
        "add_price": "💰 Enter <b>price</b> (number):",
        "add_photo": "📷 Send a <b>photo</b> or /skip:",
        "add_description": "📄 Enter <b>description</b>:",
        "invalid_price": "⚠️ Please enter a valid number.",
        "product_added": "✅ Product added!",
        "delete_choose": "🗑 Tap a product to delete:",
        "product_deleted": "🗑 Product deleted",
        "stats_title": "📊 <b>Statistics</b>",
        "stats_orders": "Orders",
        "stats_revenue": "Revenue",
        "stats_top": "Top products",
        "ai_welcome": "🤖 <b>AI Consultant</b>\n\nHi! Ask me anything about our sneakers, your orders or delivery. Type /cancel to exit.",
        "ai_error": "⚠️ Sorry, I can't answer right now. Please try again.",
        "ai_no_orders": "(no orders yet)",
        "btn_exit": "⬅️ Exit",
    },
    "ru": {
        "choose_language": "🌐 Выберите язык:",
        "language_set": "✅ Язык переключён на русский",
        "menu": "👟 <b>SneakerShop</b>\n\nЧто будем искать сегодня?",
        "welcome": "👟 <b>Добро пожаловать в SneakerShop!</b>\n\nЛюбимые кроссовки с быстрой доставкой 🚚\nВыбирайте в меню ниже.\n\n💡 /menu — открыть меню в любой момент",
        "btn_catalog": "🛍 Каталог",
        "btn_cart": "🛒 Корзина",
        "btn_orders": "🧾 Мои заказы",
        "btn_ai": "🤖 AI-консультант",
        "btn_language": "🌐 Язык",
        "soon": "🚧 Скоро будет",
        "catalog_title": "🛍 <b>Каталог</b>\n\nВыберите категорию:",
        "in_stock": "В наличии",
        "empty_category": "В этой категории пока нет товаров.",
        "btn_add_cart": "🛒 В корзину",
        "btn_categories": "⬅️ Категории",
        "btn_menu": "🏠 Меню",
        "cart_title": "🛒 <b>Ваша корзина</b>",
        "cart_empty": "🛒 Ваша корзина пуста.",
        "cart_total": "Итого",
        "added_to_cart": "✅ Добавлено в корзину",
        "btn_checkout": "💳 Оформить заказ",
        "btn_clear": "🗑 Очистить корзину",
        "checkout_name": "📝 Введите ваше <b>имя и фамилию</b>:",
        "checkout_phone": "📞 Теперь введите <b>номер телефона</b>:",
        "checkout_address": "🏠 И наконец, <b>адрес доставки</b>:",
        "checkout_confirm": "🧾 <b>Подтвердите заказ:</b>",
        "order_placed": "✅ Заказ #{id} оформлен!\nМы скоро свяжемся с вами. Спасибо! 🙌",
        "order_cancelled": "❌ Заказ отменён.",
        "btn_confirm": "✅ Подтвердить",
        "btn_cancel": "❌ Отмена",
        "orders_title": "🧾 <b>Мои заказы</b>",
        "orders_empty": "🧾 У вас пока нет заказов.",
        "status_new": "🆕 Новый",
        "status_paid": "💳 Оплачен",
        "status_shipped": "🚚 Отправлен",
        "status_done": "✅ Выполнен",
        "status_cancelled": "❌ Отменён",
        "admin_title": "🛠 <b>Админ-панель</b>",
        "admin_orders": "📦 Заказы",
        "admin_add_product": "➕ Добавить товар",
        "admin_stats": "📊 Статистика",
        "admin_no_orders": "Заказов пока нет.",
        "admin_no_products": "Товаров пока нет.",
        "status_changed": "✅ Статус обновлён",
        "btn_back": "⬅️ Назад",
        "admin_delete": "🗑 Удалить товар",
        "add_choose_category": "🗂 Выберите категорию:",
        "add_name": "📝 Введите <b>название</b> товара:",
        "add_brand": "🏷 Введите <b>бренд</b>:",
        "add_price": "💰 Введите <b>цену</b> (число):",
        "add_photo": "📷 Отправьте <b>фото</b> или /skip:",
        "add_description": "📄 Введите <b>описание</b>:",
        "invalid_price": "⚠️ Введите корректное число.",
        "product_added": "✅ Товар добавлен!",
        "delete_choose": "🗑 Нажмите на товар для удаления:",
        "product_deleted": "🗑 Товар удалён",
        "stats_title": "📊 <b>Статистика</b>",
        "stats_orders": "Заказов",
        "stats_revenue": "Выручка",
        "stats_top": "Топ товаров",
        "ai_welcome": "🤖 <b>AI-консультант</b>\n\nПривет! Спроси про наши кроссовки, твои заказы или доставку. Для выхода — /cancel.",
        "ai_error": "⚠️ Извините, сейчас не могу ответить. Попробуйте ещё раз.",
        "ai_no_orders": "(заказов пока нет)",
        "btn_exit": "⬅️ Выход",
    },
}


def t(key: str, lang: str) -> str:
    return TEXTS.get(lang, TEXTS[DEFAULT_LANG]).get(key, key)


def status_label(status: str, lang: str) -> str:
    return t(f"status_{status}", lang)


STATUSES = ("new", "paid", "shipped", "done", "cancelled")
